[package]
name = "cosmic-transmission"
version = "0.3.4"
edition = "2024"
license = "GPL-3.0-only"
description = "COSMIC applet for controlling Transmission"

[dependencies]
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["process", "time"] }
zbus = { version = "5.15", default-features = false, features = ["tokio"] }
cosmic-config = { git = "https://github.com/pop-os/libcosmic.git", package = "cosmic-config", features = ["dbus", "tokio"] }

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic.git"
default-features = false
features = [
    "applet",
    "applet-token",
    "dbus-config",
    "multi-window",
    "tokio",
    "wayland",
    "winit",
]
