[package]
name = "cosmic-transmission"
version = "0.4.1"
edition = "2024"
license = "GPL-3.0-only"
description = "COSMIC applet for controlling Transmission"
default-run = "cosmic-transmission"

[dependencies]
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
secret-service = { version = "5.2", default-features = false, features = ["rt-tokio-crypto-rust"] }
secrecy = "0.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["serde", "v4"] }
tokio = { version = "1", features = ["time", "macros", "rt"] }
tracing = "0.1"
zbus = { version = "5.15", default-features = false, features = ["tokio"] }
zbus_polkit = { version = "5.1.0", default-features = false, features = ["tokio"] }
cosmic-config = { git = "https://github.com/pop-os/libcosmic.git", rev = "7e82198ab1aba712640b0167e58ad37bf03012ca", package = "cosmic-config", features = ["dbus", "tokio"] }

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic.git"
rev = "7e82198ab1aba712640b0167e58ad37bf03012ca"
default-features = false
features = [
"applet",
"applet-token",
"dbus-config",
"multi-window",
"tokio",
"wayland",
"winit",
]